name            'h0tbird-ntp'
version         '0.0.1'
source          'https://github.com/h0tbird/puppet-ntp'
author          'Marc Villacorta'
license         'GPL'
summary         'NTP Module'
description     'Manages the NTP service.'
project_page    'https://github.com/h0tbird/puppet-ntp'
